### ISSUE TITLE
Set matplot lib to ggplot look

### ISSUE THREAD

**Issue by johnsanterre** [dssg/diogenes#13]
plt.style.use('ggplot')

aka
http://matplotlib.org/users/style_sheets.html

**Comment by johnsanterre** [comment]
looks like the only place its needed is in after import line 14

**Comment by zar1** [comment]
As per http://stackoverflow.com/questions/27204646/matplotlib-pyplot-has-no-attribute-style, plt.style is a relatively new feature. We will run the line conditionally on what version of matplotlib the user has.

**Comment by zar1** [comment]
Fixed in d24e6396906eba4cfd44081dc5a3ca825c8f4c4e
