### ISSUE TITLE
csv failure on test

### ISSUE THREAD

**Issue by johnsanterre** [dssg/diogenes#6]
FAIL: test_sliding_windows (test_grid_search.TestGridSearch)
FAIL: test_make_csv (test_grid_search.TestGridSearch)
FAIL: test_subsetting (test_grid_search.TestGridSearch)

**Comment by zar1** [comment]
The common link is that these all try to test against reference csvs. Also, these pass for me, so it looks like the way I make csvs is different from the way that John does. I guess we just can't test csvs like that.

**Comment by zar1** [comment]
After removing csvs from the suite, we still get failures for test_sliding_windows and test_subsetting. I guess something else is wrong.

**Comment by zar1** [comment]
I believe we fixed this and forgot to close the issue
